<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOQZxCum\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOQZxCum/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOQZxCum.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOQZxCum\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOQZxCum\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OQZxCum',
    'container.build_id' => '1dd2eb14',
    'container.build_time' => 1557313533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOQZxCum');
